[tool.poetry]
name = "yocto-jr"
version = "0.1.0"
description = "yocto base embedded linux"
authors = ["Javad Ramezanzadeh"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
kas = "^4.0"
pyyaml = "5.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
